version: '3.8'

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: lilyiker
      MYSQL_DATABASE: music_db
      LANG: C.UTF_8
    ports:
      - '3307:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - music_data:/var/lib/mysql
      - ./backend/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8787:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - net
    depends_on:
      - mysql

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - '6768:6768'
    networks:
      - net
    depends_on:
      mysql:
        condition: service_healthy
  
  nginx:
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
    depends_on:
      - backend

networks:
  net:
    driver: bridge

volumes:
  music_data: