server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: Music Streaming Platform
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

jwt:
  accessExpiryTime: ${JWT_ACCESS_EXPIRY_TIME}
  refreshExpiryTime: ${JWT_REFRESH_EXPIRY_TIME}
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}


